### ISSUE TITLE
IISWebAppMgmt: Invalid thumbprint on HTTP

### ISSUE THREAD

**Issue by ironicnet** [microsoft/azure-pipelines-extensions#173]
We are trying to manage a website using HTTP.
This is how it looks
![image](https://cloud.githubusercontent.com/assets/822050/21697268/500d469e-d370-11e6-8712-fa7eb63c8d25.png)

When running the task the following exception raises:
```
2017-01-05T20:47:16.6979277Z Executing the powershell script: C:\-------\_work\_tasks\IISWebAppMgmt_0f5cd14f-3c01-4d5c-8f7a-eb96c5738dcc\1.3.3\Main.ps1
 
2017-01-05T20:47:17.1979156Z ##[error]System.Management.Automation.RuntimeException: Invalid thumbprint. Length is not 40 characters or contains invalid characters. ---> System.Management.Automation.RuntimeException: Invalid thumbprint. Length is not 40 characters or contains invalid characters.
 
2017-01-05T20:47:17.1979156Z    --- End of inner exception stack trace ---
 
2017-01-05T20:47:17.1979156Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
 
2017-01-05T20:47:17.1979156Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
 
2017-01-05T20:47:17.1979156Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
 
2017-01-05T20:47:17.1979156Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2017-01-05T20:47:17.1979156Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
 
2017-01-05T20:47:17.1979156Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
 
2017-01-05T20:47:17.1979156Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
```

Can someone provide some light on what may be going on?
It stopped working two days ago... 

I don't think so, but it may be related to this commit [Fixing incorrect ssl binding for if ip is given](https://github.com/Microsoft/vsts-rm-extensions/commit/528c04c13dd85314561412329dc83bfb28b0b6a1) ??

**Comment by mvvsubbu** [comment]
Can you share us full logs by variable system.debug = true

**Comment by mvvsubbu** [comment]
We have added validation for certificate thumb print and hence this error. It is expected

**Comment by cwoolum** [comment]
I'm having this issue as well. The thumbprint ‎dbc22e527d61cddb16addc34fd5e3f5ad87c7aa5 should be valid. It is 40 characters long and passes the regex ```[a-fA-F0-9]{40}```

**Comment by mvvsubbu** [comment]
Adding Arjun @arjgupta

**Comment by brainboost** [comment]
The issue caused by ? symbol, preceding the thumbprint. From my debug log:
 
##[debug]PowerShellHandler.Execute - AddParameter(HostNameWithHttp=)
##[debug]PowerShellHandler.Execute - AddParameter(HostNameWithSNI=)
##[debug]PowerShellHandler.Execute - AddParameter(SSLCertThumbPrint=?9a81d935c4a07081f596a9576b5960a277b9c6d7)
##[debug]PowerShellHandler.Execute - AddParameter(CreateAppPool=true)

Check your thumbprint value attentively and (as in my case) retype first characters manually. It helped me.

**Comment by cwoolum** [comment]
Just confirmed that copy/past is causing the problem. Deleting the first few characters and manually typing fixes it.

**Comment by vankampenp** [comment]
Same here, deleting the first few characters and retyping them worked. And off course removing the spaces.

**Comment by danielstefanescu** [comment]
Almost the same here: deleting the first characters didn't work; deleting everything after pasting the thumbprint and retyping it didn't work.
I had to recreate the task and manually type thumbprint in order to work.

**Comment by kikiprinci** [comment]
I had the same error, and the unique way to solve this went:
- Create a new task of WinRM - IIS WebApp Managment
- Fill in again all of our variables
-Rewrite manually the thumbprint

When I rewriteed the thumbprint in a previous task didn't run correctly

**Comment by asranja** [comment]
@kikiprinci can you share the error that you received.

**Comment by kikiprinci** [comment]
![image](https://user-images.githubusercontent.com/9587938/36590456-06930b06-188f-11e8-9013-83131cb1a598.png)

![image](https://user-images.githubusercontent.com/9587938/36590536-41d4ef9a-188f-11e8-8153-9b1bce30519c.png)

**Comment by asranja** [comment]
@kikiprinci Can you paste the thumbprint in a [unicode converter](https://r12a.github.io/apps/conversion/) and see if there are invalid characters at the beginning or end. You can refer to a similar [issue ](https://github.com/Microsoft/vsts-tasks/issues/5048) for a Deployment Group based IIS Web App Manage task.  Please let us know if you still face issues.
