### ISSUE TITLE
VisualStudioRemoteDeployer SerializationException

### ISSUE THREAD

**Issue by GeorgeTsiokos** [microsoft/azure-pipelines-extensions#384]
__PowerShell on Target Machines__
Executes less than one minute, and reports
```
Deployment aborted unexpectedly. This might be due to an unplanned restart of target machine. Consult the logs if any on the target machine to fix the issues and retry the operation.
```

__On the target machine__

> Error __Application Error__ 1000 (100)
```
Faulting application name: VisualStudioRemoteDeployer.exe, version: 16.129.27302.1, time stamp: 0x5a4b4899
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x184c
Faulting application start time: 0x01d3a44c1161b885
Faulting application path: C:\Windows\DtlDownloads\VisualStudioRemoteDeployer0158875b-8fc1-48e8-b823-422875383124\VisualStudioRemoteDeployer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 6e3f060a-103f-11e8-80ec-005056962902
```
> Error __.NET Runtime__ 1026
```
Application: VisualStudioRemoteDeployer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.Serialization.SerializationException
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(System.Runtime.Serialization.DataContract, System.Runtime.Serialization.XmlWriterDelegator, System.Object, Boolean, System.RuntimeTypeHandle, System.Type)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.RuntimeTypeHandle, System.Type, Int32, System.RuntimeTypeHandle, System.Type)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(System.Runtime.Serialization.XmlWriterDelegator, System.Object, Boolean, Boolean, Int32, System.RuntimeTypeHandle)
   at DynamicClass.WriteDeploymentResponseToXml(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.XmlObjectSerializerWriteContext, System.Runtime.Serialization.ClassDataContract)
   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.XmlObjectSerializerWriteContext)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(System.Runtime.Serialization.DataContract, System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.RuntimeTypeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(System.Runtime.Serialization.DataContract, System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.RuntimeTypeHandle)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.DataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.DataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.DataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(System.Xml.XmlDictionaryWriter, System.Object)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(System.IO.Stream, System.Object)
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.XmlHelper.Serialize[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.WriteResponseXMLFile(Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Interfaces.DeploymentResponse, Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Interfaces.IXmlSerializer)
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

> procdump -w VisualStudioRemoteDeployer.exe
```xml
<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical">
  <TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier>
  <Description>Unhandled exception</Description><AppDomain>VisualStudioRemoteDeployer.exe</AppDomain>
  <Exception>
    <ExceptionType>System.Runtime.Serialization.SerializationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
    <Message>Type 'System.Management.ManagementException' with data contract name 'ManagementException:http://schemas.datacontract.org/2004/07/System.Management' is not expected. Consider using a DataContractResolverif you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.</Message>
    <StackTrace>   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)   at WriteDeploymentResponseToXml(XmlWriterDelegator , Object , XmlObjectSerializerWriteContext , ClassDataContract )   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj,RuntimeTypeHandle declaredTypeHandle)   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.XmlHelper.Serialize[T](T managedClassObject)   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.WriteResponseXMLFile(DeploymentResponse deploymentResponse, IXmlSerializer xmlHelper)   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.RemoteDeployerService.Execute()   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)   at System.Threading.ThreadHelper.ThreadStart()</StackTrace>
  </Exception>
</TraceRecord>
```
Dump available upon request.

**Comment by bkeastmond** [comment]
I am experiencing a similar issue (the error is the same). 

The script runs; the task in the script creates and/or adds content to the file.

[remoteVSTSissue.txt](https://github.com/Microsoft/vsts-rm-extensions/files/1852462/remoteVSTSissue.txt)
[script-for-deploy.txt](https://github.com/Microsoft/vsts-rm-extensions/files/1852466/script-for-deploy.txt)

It appears that it errors out after running the script because of the errors encountered with the unexpected value in the contract.

We have a release step from agent2 (capabilities below) that is executing the test script above using PowershellOnTargetMachines as the task on the agent1 machine (capabilities below). In this configuration we get the described error in this case; the file does get created. However, if we reverse the configuration and run from agent1 to agent2 machine, the entire process does not error out and succeeds the release succeeds and the file is created by the test script. 

[agent1-capability.txt](https://github.com/Microsoft/vsts-rm-extensions/files/1852506/agent1-capability.txt)
[agent2-capability.txt](https://github.com/Microsoft/vsts-rm-extensions/files/1852508/agent2-capability.txt)

**Comment by asranja** [comment]
@GeorgeTsiokos @bkeastmond Can you try using the latest version of the PowerShell On Target Machines task and let us know the results?

**Comment by Ajay-MS** [comment]
Did you get chance to tryout the suggestion provided by @asranja

**Comment by vincentdass** [comment]
Closing the issue as there is no response.
Please feel free to reopen/ start a new thread.

**Comment by GeorgeTsiokos** [comment]
Unfortunately I can't re-test - these workloads were moved from .NET Framework to .NET Core and run in Kubernetes on Linux instead of Windows.

**Comment by arcdev** [comment]
In our case, this happened due to a corrupt WMI repository.
It seems that the VisualStudioRemoteDeployer.exe tries to connect to `\\localhost\root\CIMV2`
then select SELECT UUID FROM Win32_ComputerSystemProduct.
Because the `CIMV2` namespace was corrupt, a `System.Management.ManagementException` was thrown and could not be serialized.

I was able to find this part of the exception in a full crash dump:
```
Exception : System.Runtime.Serialization.SerializationException: Type 'System.Management.ManagementException' with data contract name 'ManagementException:http://schemas.datacontract.org/2004/07/System.Management' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.
```

This article provided the information on how to determine which parts of the WMI repo were bad and how to resolve them.
https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-missing-or-failing-wmi-providers-or-invalid-wmi-class/ba-p/375485
