### ISSUE TITLE
[ApexSQL DevOps toolkit - Build Task] Error: Cannot find module 'azure-pipelines-task-lib/task' 

### ISSUE THREAD

**Issue by AltugYildirim** [microsoft/azure-pipelines-extensions#743]
Hi everyone,

I've got this error below.  I've tried on both Hosted/Private agent pools. 

```
##[section]Starting: ApexSQL DevOps toolkit - Build
==============================================================================
Task         : ApexSQL DevOps toolkit - Build
Description  : Build database from source control repository.
Version      : 1.0.2
Author       : ApexSQL LLC
Help         : 
==============================================================================
module.js:471
    throw err;
    ^

Error: Cannot find module 'azure-pipelines-task-lib'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Agent\_work\_tasks\ApexSqlDotBuild_12fa4359-9c97-46ea-bc65-af045384dade\1.0.2\bootstrap.js:19:52)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
##[error]Exit code 1 returned from process: file name 'C:\Agent\externals\node\bin\node.exe', arguments '"C:\Agent\_work\_tasks\ApexSqlDotBuild_12fa4359-9c97-46ea-bc65-af045384dade\1.0.2\bootstrap.js"'.
##[section]Finishing: ApexSQL DevOps toolkit - Build
```

**Comment by chshrikh** [comment]
ApexSQL  task is not belongs to this repo, please see if [this doc](https://knowledgebase.apexsql.com/how-to-setup-continuous-integration-and-continuous-delivery-tasks-using-the-apexsql-devops-toolkit-azure-devops-server-tfs-azure-devops-services-plugin/) can help you to find the guidance for you
