### ISSUE TITLE
Change provider doesn't remove reference to previous one

### ISSUE THREAD

**Issue by tasb** [microsoft/azure-pipelines-extensions#762]
When you configur plan or validte task to one provider (for instance AWS) and then change to other (Azure) the reference for service connection is not removed and if you try to import and export the pipeline you get errors.

![image](https://user-images.githubusercontent.com/415105/72386774-4d172680-3722-11ea-8da0-ba3c205b7c07.png)

**Comment by tasb** [comment]
More details and the issue is bigger.

I exported the pipeline and imported on another organization.

On new imported pipeline I change the config on terraform task to use new Azure Connection. On UI everything seems fine but when I run the pipeline I get this error:

Exception Message: The pipeline is not valid. Job Phase_1: Step TerraformTaskV11 input backendServiceArm references service connection 2c98f46c-fd86-4f7f-83a5-a59f9a4ac3a7 which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.,Job Phase_1: Step TerraformTaskV11 input backendServiceAWS references service connection 79d88d76-b207-4ad1-8f72-0e4775b2320e which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. (type PipelineValidationException)
Exception Stack Trace:    at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidatePipelineProcess(IVssRequestContext requestContext, Guid scopeIdentifier, Int32 definitionId, Guid planId, PipelineEnvironment environment, PipelineProcess pipeline, BuildOptions options) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 6266
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.ValidateProcess(IVssRequestContext requestContext, Guid scopeIdentifier, TaskOrchestrationOwner definition, Guid planId, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions options) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 6187
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.CreatePlan(IVssRequestContext requestContext, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String pipelineInitializationLog) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 351
   at Microsoft.TeamFoundation.DistributedTask.Orchestration.Server.TaskHub.RunPlan(IVssRequestContext requestContext, TaskAgentPoolReference pool, Guid scopeIdentifier, Guid planId, String planGroup, PlanTemplateType templateType, Uri artifactUri, IOrchestrationEnvironment environment, IOrchestrationProcess process, BuildOptions validationOptions, Guid requestedForId, TaskOrchestrationOwner definitionReference, TaskOrchestrationOwner ownerReference, String pipelineInitializationLog) in D:\v2.0\P1\_work\7\s\DistributedTask\Sdk\Server\TaskHub.cs:line 1508
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.DistributedTask.PipelineOrchestrator.StartDeployment(AutomationEngineInput input) in D:\v2.0\P1\_work\7\s\ReleaseManagement\Service\ReleaseManagement2\Server\DistributedTask\PipelineOrchestrator.cs:line 77
   at Microsoft.VisualStudio.Services.ReleaseManagement.Server.Processors.DeployPhaseRunner.Run(Release release, ReleaseEnvironment releaseEnvironment, ReleaseEnvironmentStep deployStep, DeployPhaseSnapshot snapshotToProcess) in D:\v2.0\P1\_work\7\s\ReleaseManagement\Service\ReleaseManagement2\Server\Processors\DeployPhaseRunner.cs:line 222 


The reference for connection on first pipeline persists.

**Comment by Roshan-Kumar-Microsoft** [comment]
@tasb Thanks for pointing this out. We are able to reproduce this and will fix this in next release.

**Comment by lupusllc** [comment]
We found an issue where a task using "init", when cloned, will keep it's backend AWS specific values. When you change those closed tasks to plan, apply or anything else this can cause the Agent Job to fail before it can even run any tasks. It fails when those tasks have service connection value that isn't in that subscription.

If we go into the non-init tasks, change them back to "init" and remove all references in the "Amazon Web Service()AWS backend configuration" section, then move it back to plan or apply. It will clear out this data and be able to proceed normally. I'm not entirely sure if this issue is an issue with the way this task is created or if it's Azure DevOps specific.

We're using classic release pipelines and we exported and imported from another working release pipeline in another project. So far this is the only situation that has caused us any issues. I don't know if the changes here will help resolve these other issues. If not, let me know and I will open a separate issue.

![image](https://user-images.githubusercontent.com/16469173/130705515-fec585c6-8c33-4722-a431-06aa621a6624.png)

**Comment by lupusllc** [comment]
Just re-affirming, this is still an issue.
