### ISSUE TITLE
TeamCity Service Connection issue

### ISSUE THREAD

**Issue by mrpolaris** [microsoft/azure-pipelines-extensions#893]
When running a release in azure devops server 2020 with a artifact as TeamCity you get the following error

2020-12-07T17:13:16.6313652Z ##[error]Downloading artifacts failed: System.AggregateException: One or more errors occurred. (You do not have permissions to perform this operation on the service connection. An Endpoint Administrator should add you to the Endpoint Readers group of this service connection.)
 ---> Microsoft.VisualStudio.Services.Security.AccessCheckException: You do not have permissions to perform this operation on the service connection. An Endpoint Administrator should add you to the Endpoint Readers group of this service connection.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseServer.GetReleaseArtifactsFromService(Int32 releaseId, Guid projectId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.GetReleaseArtifacts(IExecutionContext executionContext)
2020-12-07T17:13:16.6348987Z ##[error]One or more errors occurred. (You do not have permissions to perform this operation on the service connection. An Endpoint Administrator should add you to the Endpoint Readers group of this service connection.)
2020-12-07T17:13:16.6360659Z ##[debug]System.AggregateException: One or more errors occurred. (You do not have permissions to perform this operation on the service connection. An Endpoint Administrator should add you to the Endpoint Readers group of this service connection.)
 ---> Microsoft.VisualStudio.Services.Security.AccessCheckException: You do not have permissions to perform this operation on the service connection. An Endpoint Administrator should add you to the Endpoint Readers group of this service connection.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseServer.GetReleaseArtifactsFromService(Int32 releaseId, Guid projectId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.GetReleaseArtifacts(IExecutionContext executionContext)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)

**Comment by mrpolaris** [comment]
I am a full admin to the service connection

**Comment by mrpolaris** [comment]
Update  Seems to only have this error when it is a release artifact type

**Comment by jcarlosg87** [comment]
hi, is this problem solved? Is there any way or configuration for it, I really appreciate your comments I am having the same problem
